# Generated by Django 4.2.7 on 2025-07-30 18:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recipient_email', models.EmailField(help_text='Email of the recipient', max_length=254)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('donation_received', 'Donation Received'), ('volunteer_application', 'Volunteer Application'), ('campaign_update', 'Campaign Update'), ('general_announcement', 'General Announcement')], max_length=50)),
                ('is_read', models.BooleanField(default=False)),
                ('reference_id', models.CharField(blank=True, help_text='ID of the related object (e.g., Donation ID, Volunteer Application ID)', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
